import { Sidebar } from "../../../components/Sidebar";
import "../../../styles.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function CollectionLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex min-h-screen">
      <Sidebar />
      <main className="flex-1 ml-3 my-3">{children}</main>
    </section>
  );
}
