import { Sidebar } from "../../../components/Sidebar";
import "../../../styles.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function CollectionLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Record<string, string>;
}) {
  return (
    <section className="flex min-h-screen">
      <Sidebar params={params} />
      <main className="flex-1 mx-3 my-3">{children}</main>
    </section>
  );
}
